version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/usr/local/app
    ports:
      - 8000:8000
    command: air -c .air.toml
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports: 
      - 5432:5432
    volumes:
      - ./.docker/postgres/volumes:/var/lib/postresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=screen-seat-api

